//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/CharacterControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterControls"",
    ""maps"": [
        {
            ""name"": ""Player 1"",
            ""id"": ""2b7a0304-cf19-46bc-9d9c-c9cfe9ccc2a0"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""d986d784-8635-43f7-9536-a62dc7b3a6d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f475ce92-a30f-4ce9-adbd-ccd043857ad6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""22f119f0-dbae-4d19-8a49-dede3fbb8e41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DirectionalInput"",
                    ""type"": ""Value"",
                    ""id"": ""130dbc91-8acb-4e50-86df-9d9704ed6c70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Light Normal"",
                    ""type"": ""Button"",
                    ""id"": ""f6f509eb-576d-4a06-9c4f-85e1d5685ca9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Normal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b0c7c1a6-e666-4795-bcf0-f08d18c42131"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light Special"",
                    ""type"": ""Button"",
                    ""id"": ""f3186820-a930-446c-9de4-5737518377a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Special"",
                    ""type"": ""Button"",
                    ""id"": ""0bb7ac76-b74c-4e61-b588-06a618144936"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""7334c2e0-962e-4b09-bfec-3b363e42d297"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""5b3d44ed-cc89-4ab1-80ba-7f27ec66cd3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Regular Parry"",
                    ""type"": ""Button"",
                    ""id"": ""085e72da-77e8-4e14-a931-315af809d410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Normal Parry"",
                    ""type"": ""Button"",
                    ""id"": ""83963b68-afc2-46a1-98c4-2f785649bc33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Parry"",
                    ""type"": ""Button"",
                    ""id"": ""7c9faff4-eff0-4b34-bfcb-1edcb3e9e5cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard/Horizontal"",
                    ""id"": ""0ad7297e-56d7-47b5-a80b-ef4a18ebb7ee"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9d628b03-f36c-4a04-9531-b53e4742ac56"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a69beb25-26f3-4d24-b5f3-fa8c8f633e14"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-Stick/Horizontal"",
                    ""id"": ""cd9a4497-cae4-4cec-b949-e60ef885bec6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.2,max=1),Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e5e563e3-4879-48b6-8dc7-1fded20a2893"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""919e5b2b-2d72-4794-af68-a4f6d7113a53"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-D-Pad/Horizontal"",
                    ""id"": ""921decd0-161d-46cb-aebf-97b318a97031"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fee59d36-b898-4cef-b67f-620c57d5ae76"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ddc85a3b-8e60-4019-abae-419641a9fdcb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e737280e-d72c-46da-a089-da9d50c4d8f1"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e50514f0-4e18-4df1-ae52-c6c031002264"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard/2DVector"",
                    ""id"": ""e8559e92-2884-4817-9b91-ccdc2add5081"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""57fdc9ee-8f31-470b-b313-631b749b9f59"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""85d4c17d-89cf-4cc6-a885-236cbc972124"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""05392961-6a48-4d49-90c4-eb4189e3ecbc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""749306c0-5f04-45bc-b5c3-80e955fb5f61"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-Stick/2DVector"",
                    ""id"": ""93f185d3-1e70-4975-b33a-8e0857cf04ba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ccbc742-238a-42bc-8a8f-0c69c09fcaf2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0631b3cf-b7c9-47f1-9aaf-f0955940b557"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0ae8b750-7427-4498-861c-ba64bc95ccfe"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9155a25b-9903-4cc1-93fc-58f239c8416e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-D-Pad/2DVector"",
                    ""id"": ""341e34be-29e0-4d1b-a36b-26f6535bdcea"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1f5f13bd-86d2-43df-86c9-82b9c930d99f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bbe61757-b3f8-4a9f-b97a-b155d07d2247"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""da624744-60c0-4628-a162-8be6fc39fca6"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""596ab4ac-0c2c-4024-9cfa-bcb24b7ab8e3"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5f18baa3-3fdf-4034-bbdd-58ad7bf14f13"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb84704d-d3af-407e-a947-f60e24b9912f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff3d69f4-b5ce-4dec-ae5a-d2f0d5c8bfc0"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0296c1fa-50eb-4a83-b0b3-33ff99b31d01"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e876495b-ef92-4d7b-be4a-009eee1558aa"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66d1e88f-d11e-469b-8f70-d693e84e5311"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f250b6bd-ca7d-45fe-8766-06666957cace"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84680f4e-9d27-449b-8713-03fdd0989706"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a33d527-41fd-4cf3-92bc-ae14f0806a55"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4eff7804-3326-4c17-a647-94a330fb5862"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfd9f51-82cc-4dd3-be38-4bfdc855adac"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df845f77-e49b-46f9-9c8e-1fd78345a1e9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a3748a00-6418-4594-b45d-94497943a244"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""760f7032-c0d4-411b-ab92-8298e76c3796"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""fd408c17-3401-4ea8-b01c-7fc274575a14"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""68f48599-8c9f-4399-b16a-20a37018d39c"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a5da4721-40e6-41c0-ae58-89ee15cf3954"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""909281f5-2c18-4e8b-a3a7-625bb0aff773"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""e51334b1-b092-4e7b-abcb-f87a3794c4a0"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""193c30b4-5ac2-4ef8-ad4c-477eb9bebddb"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""3f6feee2-7360-46fd-a16b-f8279ce0ee0c"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""308ab2da-72b9-48fb-a285-75d3ec942311"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a6e155b3-4cd4-481c-805b-85e9fb078ab0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""32ebf71d-3d04-4777-bee5-32f03eb69fbe"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e865e90c-5e1f-4be0-8e9f-6e424727d268"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86cb8baf-8850-40e5-8132-5b91d8204a7c"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player 2"",
            ""id"": ""70788146-ee98-4794-96be-ec098d30ee79"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""5f964765-e3bf-4eba-b98d-9ae5e658d9f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""90d20006-5db9-450d-8b8c-5469234d4178"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""8e62a75a-3656-40da-8750-6d8e278f0000"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DirectionalInput"",
                    ""type"": ""Value"",
                    ""id"": ""7d92cbc2-16f4-483b-96db-e3cb494fea37"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Light Normal"",
                    ""type"": ""Button"",
                    ""id"": ""71a7f703-d13a-46f0-b75d-5fbbd2c82ef1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Normal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2333e793-a9fb-46ef-a3f7-9579a3d37b04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light Special"",
                    ""type"": ""Button"",
                    ""id"": ""a3ad8131-aa1e-4c2a-8e94-66a9eee10a7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Special"",
                    ""type"": ""Button"",
                    ""id"": ""b4923dda-19fd-43af-b1c4-dfdab8b5956e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""1b1d43dd-ce7d-4e98-8f5d-30ef67164f5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""1cc4acd1-43db-4f16-9985-9e4803cf0051"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Normal Parry"",
                    ""type"": ""Button"",
                    ""id"": ""85919a31-03e0-4f90-a32b-58eaa2564214"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Parry"",
                    ""type"": ""Button"",
                    ""id"": ""be319d53-81dd-469f-96dd-a921ee1e7019"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab Parry"",
                    ""type"": ""Button"",
                    ""id"": ""34c9e734-8485-48f0-9075-fe9b71318f56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard/Horizontal"",
                    ""id"": ""9a9b1a6f-98bc-41e1-96bd-5bceb070136a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a84f2102-9532-4666-8d6a-f89e15da9085"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fd2746e4-56b0-4470-b25a-3310da2ecd01"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-Stick/Horizontal"",
                    ""id"": ""7571473e-8f59-464a-872b-3696a9873c4d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.2,max=1),Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""75af09d8-ed44-4142-a767-bf0b431b492d"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5efe980e-f348-4105-8121-6a2297a45e2e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-D-Pad/Horizontal"",
                    ""id"": ""979290e7-1d71-458e-b78c-6350c9fcef1d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""266739aa-22ea-4121-871d-e38f295830a5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""54240886-61d8-49fe-a35a-ffc81fc4bc1f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cc161ea1-92d4-4455-9699-049312d458b9"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8a7d28-4365-4bcb-acd6-ae6cf11ca2ae"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard/2DVector"",
                    ""id"": ""f2664077-d6ee-43c4-a91f-da9ce6019df0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""54a9e24a-f769-41d8-bd47-3ebb7d1362f9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f0da4922-f582-44e2-9e26-fb7ce198901e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""62233729-47d8-4a1f-a787-98cff3dd330d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""413540de-c61e-4db7-b2fc-4f2ce6e09d11"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-Stick/2DVector"",
                    ""id"": ""ad93863c-0870-4cae-b2d8-1e5f8bd6fadb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone(min=0.2,max=1),NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""18102dad-9be6-4052-a381-1dd6c62c9e66"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""303a631d-cd79-40fa-8a87-527881e0a91f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""91fc9a89-25c5-4e4b-b7e2-b304606d27b1"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""23b065b3-dd4d-423b-a486-198b7d3a61e8"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-D-Pad/2DVector"",
                    ""id"": ""5224326d-ea25-48ed-a2c4-8da03e671b6d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9e66fbaf-8b02-4957-aa22-5d5a9e1a84fb"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fe47c86a-4ddd-4ae6-8b78-24d81e3825e1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b52c3b7d-cbd9-4e72-8624-a773d74a39b0"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5bc87327-0ae1-4585-a374-4d5b0e7fa6cc"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ce2f2e95-1ff4-402a-bd53-d98424dad9aa"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40e78a88-fcf5-4208-a8de-d2a52422fe3c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41968d0b-3123-4d75-917c-cdcfe8fbb6c6"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55daa3ff-87bf-48a9-84e7-2802e587433a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1ebd0ff-c2cd-4de7-8f6e-916ee18374e7"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de0ce63c-be56-4701-8578-4ad70875b9c3"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03767945-b339-4fe9-8512-ac0ba2a82e14"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fbd566d-c4c5-4415-9f7f-89b3309d4e79"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e918d804-09fc-4220-9d8e-d9897b9f4b1b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9ef5f34-7376-4e78-bc27-da9ebb683e1f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59844182-978f-4365-8b64-8d6deae36dff"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a4f3f58-bc6b-42f6-934e-34964188634d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""8c25af45-5342-4149-9d3a-f1064aca780e"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e049e893-3310-4ee0-b3c3-88d886158b09"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""4d40315a-6bf5-4121-9cff-4fff162d0a26"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""24dfc6a4-2e88-40c1-923a-190a79491889"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""fb6eae2d-661b-4644-a5aa-fd481092685a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""1dbc6846-b5af-407b-a8c6-0dd1c8f3293a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""45110dfb-2d0a-486c-9754-506d9557151a"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d892ac63-ea46-4cc0-8040-2541a3c945d7"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""37bca41b-31cd-4ea8-bd83-2793c00be0d9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""746398c3-bcfc-42ca-92d2-de7afdb2f530"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9e4a86ec-7abd-4625-8b4d-5d6a6ac162a6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""ccb324b7-69b7-49f6-bcb7-44affa6fd4eb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""daed926d-bada-47f5-a9af-c0e4557c0060"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7bdd4ad5-d5b7-48db-ba49-8a3ff96eb36f"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""974dbf4f-2236-426b-8173-b8c060973be0"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""87661cbd-f173-4705-8c3f-ff50c7e618ae"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8ab633e1-9318-421c-97d4-d1b297906d66"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""05264e56-8662-48a3-b318-96816c5fedb0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player 1
        m_Player1 = asset.FindActionMap("Player 1", throwIfNotFound: true);
        m_Player1_Move = m_Player1.FindAction("Move", throwIfNotFound: true);
        m_Player1_Jump = m_Player1.FindAction("Jump", throwIfNotFound: true);
        m_Player1_Dash = m_Player1.FindAction("Dash", throwIfNotFound: true);
        m_Player1_DirectionalInput = m_Player1.FindAction("DirectionalInput", throwIfNotFound: true);
        m_Player1_LightNormal = m_Player1.FindAction("Light Normal", throwIfNotFound: true);
        m_Player1_HeavyNormal = m_Player1.FindAction("Heavy Normal", throwIfNotFound: true);
        m_Player1_LightSpecial = m_Player1.FindAction("Light Special", throwIfNotFound: true);
        m_Player1_HeavySpecial = m_Player1.FindAction("Heavy Special", throwIfNotFound: true);
        m_Player1_Guard = m_Player1.FindAction("Guard", throwIfNotFound: true);
        m_Player1_Grab = m_Player1.FindAction("Grab", throwIfNotFound: true);
        m_Player1_RegularParry = m_Player1.FindAction("Regular Parry", throwIfNotFound: true);
        m_Player1_NormalParry = m_Player1.FindAction("Normal Parry", throwIfNotFound: true);
        m_Player1_SpecialParry = m_Player1.FindAction("Special Parry", throwIfNotFound: true);
        // Player 2
        m_Player2 = asset.FindActionMap("Player 2", throwIfNotFound: true);
        m_Player2_Move = m_Player2.FindAction("Move", throwIfNotFound: true);
        m_Player2_Jump = m_Player2.FindAction("Jump", throwIfNotFound: true);
        m_Player2_Dash = m_Player2.FindAction("Dash", throwIfNotFound: true);
        m_Player2_DirectionalInput = m_Player2.FindAction("DirectionalInput", throwIfNotFound: true);
        m_Player2_LightNormal = m_Player2.FindAction("Light Normal", throwIfNotFound: true);
        m_Player2_HeavyNormal = m_Player2.FindAction("Heavy Normal", throwIfNotFound: true);
        m_Player2_LightSpecial = m_Player2.FindAction("Light Special", throwIfNotFound: true);
        m_Player2_HeavySpecial = m_Player2.FindAction("Heavy Special", throwIfNotFound: true);
        m_Player2_Guard = m_Player2.FindAction("Guard", throwIfNotFound: true);
        m_Player2_Grab = m_Player2.FindAction("Grab", throwIfNotFound: true);
        m_Player2_NormalParry = m_Player2.FindAction("Normal Parry", throwIfNotFound: true);
        m_Player2_SpecialParry = m_Player2.FindAction("Special Parry", throwIfNotFound: true);
        m_Player2_GrabParry = m_Player2.FindAction("Grab Parry", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player 1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_Move;
    private readonly InputAction m_Player1_Jump;
    private readonly InputAction m_Player1_Dash;
    private readonly InputAction m_Player1_DirectionalInput;
    private readonly InputAction m_Player1_LightNormal;
    private readonly InputAction m_Player1_HeavyNormal;
    private readonly InputAction m_Player1_LightSpecial;
    private readonly InputAction m_Player1_HeavySpecial;
    private readonly InputAction m_Player1_Guard;
    private readonly InputAction m_Player1_Grab;
    private readonly InputAction m_Player1_RegularParry;
    private readonly InputAction m_Player1_NormalParry;
    private readonly InputAction m_Player1_SpecialParry;
    public struct Player1Actions
    {
        private @CharacterControls m_Wrapper;
        public Player1Actions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player1_Move;
        public InputAction @Jump => m_Wrapper.m_Player1_Jump;
        public InputAction @Dash => m_Wrapper.m_Player1_Dash;
        public InputAction @DirectionalInput => m_Wrapper.m_Player1_DirectionalInput;
        public InputAction @LightNormal => m_Wrapper.m_Player1_LightNormal;
        public InputAction @HeavyNormal => m_Wrapper.m_Player1_HeavyNormal;
        public InputAction @LightSpecial => m_Wrapper.m_Player1_LightSpecial;
        public InputAction @HeavySpecial => m_Wrapper.m_Player1_HeavySpecial;
        public InputAction @Guard => m_Wrapper.m_Player1_Guard;
        public InputAction @Grab => m_Wrapper.m_Player1_Grab;
        public InputAction @RegularParry => m_Wrapper.m_Player1_RegularParry;
        public InputAction @NormalParry => m_Wrapper.m_Player1_NormalParry;
        public InputAction @SpecialParry => m_Wrapper.m_Player1_SpecialParry;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Dash.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @DirectionalInput.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @LightNormal.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @LightNormal.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @LightNormal.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @HeavyNormal.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @LightSpecial.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @HeavySpecial.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @Guard.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Grab.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @RegularParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @RegularParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @RegularParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @NormalParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @NormalParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @NormalParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @SpecialParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @DirectionalInput.started += instance.OnDirectionalInput;
                @DirectionalInput.performed += instance.OnDirectionalInput;
                @DirectionalInput.canceled += instance.OnDirectionalInput;
                @LightNormal.started += instance.OnLightNormal;
                @LightNormal.performed += instance.OnLightNormal;
                @LightNormal.canceled += instance.OnLightNormal;
                @HeavyNormal.started += instance.OnHeavyNormal;
                @HeavyNormal.performed += instance.OnHeavyNormal;
                @HeavyNormal.canceled += instance.OnHeavyNormal;
                @LightSpecial.started += instance.OnLightSpecial;
                @LightSpecial.performed += instance.OnLightSpecial;
                @LightSpecial.canceled += instance.OnLightSpecial;
                @HeavySpecial.started += instance.OnHeavySpecial;
                @HeavySpecial.performed += instance.OnHeavySpecial;
                @HeavySpecial.canceled += instance.OnHeavySpecial;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
                @RegularParry.started += instance.OnRegularParry;
                @RegularParry.performed += instance.OnRegularParry;
                @RegularParry.canceled += instance.OnRegularParry;
                @NormalParry.started += instance.OnNormalParry;
                @NormalParry.performed += instance.OnNormalParry;
                @NormalParry.canceled += instance.OnNormalParry;
                @SpecialParry.started += instance.OnSpecialParry;
                @SpecialParry.performed += instance.OnSpecialParry;
                @SpecialParry.canceled += instance.OnSpecialParry;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player 2
    private readonly InputActionMap m_Player2;
    private IPlayer2Actions m_Player2ActionsCallbackInterface;
    private readonly InputAction m_Player2_Move;
    private readonly InputAction m_Player2_Jump;
    private readonly InputAction m_Player2_Dash;
    private readonly InputAction m_Player2_DirectionalInput;
    private readonly InputAction m_Player2_LightNormal;
    private readonly InputAction m_Player2_HeavyNormal;
    private readonly InputAction m_Player2_LightSpecial;
    private readonly InputAction m_Player2_HeavySpecial;
    private readonly InputAction m_Player2_Guard;
    private readonly InputAction m_Player2_Grab;
    private readonly InputAction m_Player2_NormalParry;
    private readonly InputAction m_Player2_SpecialParry;
    private readonly InputAction m_Player2_GrabParry;
    public struct Player2Actions
    {
        private @CharacterControls m_Wrapper;
        public Player2Actions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player2_Move;
        public InputAction @Jump => m_Wrapper.m_Player2_Jump;
        public InputAction @Dash => m_Wrapper.m_Player2_Dash;
        public InputAction @DirectionalInput => m_Wrapper.m_Player2_DirectionalInput;
        public InputAction @LightNormal => m_Wrapper.m_Player2_LightNormal;
        public InputAction @HeavyNormal => m_Wrapper.m_Player2_HeavyNormal;
        public InputAction @LightSpecial => m_Wrapper.m_Player2_LightSpecial;
        public InputAction @HeavySpecial => m_Wrapper.m_Player2_HeavySpecial;
        public InputAction @Guard => m_Wrapper.m_Player2_Guard;
        public InputAction @Grab => m_Wrapper.m_Player2_Grab;
        public InputAction @NormalParry => m_Wrapper.m_Player2_NormalParry;
        public InputAction @SpecialParry => m_Wrapper.m_Player2_SpecialParry;
        public InputAction @GrabParry => m_Wrapper.m_Player2_GrabParry;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Dash.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @DirectionalInput.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @LightNormal.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @LightNormal.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @LightNormal.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @HeavyNormal.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @LightSpecial.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @HeavySpecial.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @Guard.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Grab.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @NormalParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @NormalParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @NormalParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @SpecialParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
                @GrabParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabParry;
                @GrabParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabParry;
                @GrabParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrabParry;
            }
            m_Wrapper.m_Player2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @DirectionalInput.started += instance.OnDirectionalInput;
                @DirectionalInput.performed += instance.OnDirectionalInput;
                @DirectionalInput.canceled += instance.OnDirectionalInput;
                @LightNormal.started += instance.OnLightNormal;
                @LightNormal.performed += instance.OnLightNormal;
                @LightNormal.canceled += instance.OnLightNormal;
                @HeavyNormal.started += instance.OnHeavyNormal;
                @HeavyNormal.performed += instance.OnHeavyNormal;
                @HeavyNormal.canceled += instance.OnHeavyNormal;
                @LightSpecial.started += instance.OnLightSpecial;
                @LightSpecial.performed += instance.OnLightSpecial;
                @LightSpecial.canceled += instance.OnLightSpecial;
                @HeavySpecial.started += instance.OnHeavySpecial;
                @HeavySpecial.performed += instance.OnHeavySpecial;
                @HeavySpecial.canceled += instance.OnHeavySpecial;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
                @NormalParry.started += instance.OnNormalParry;
                @NormalParry.performed += instance.OnNormalParry;
                @NormalParry.canceled += instance.OnNormalParry;
                @SpecialParry.started += instance.OnSpecialParry;
                @SpecialParry.performed += instance.OnSpecialParry;
                @SpecialParry.canceled += instance.OnSpecialParry;
                @GrabParry.started += instance.OnGrabParry;
                @GrabParry.performed += instance.OnGrabParry;
                @GrabParry.canceled += instance.OnGrabParry;
            }
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayer1Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDirectionalInput(InputAction.CallbackContext context);
        void OnLightNormal(InputAction.CallbackContext context);
        void OnHeavyNormal(InputAction.CallbackContext context);
        void OnLightSpecial(InputAction.CallbackContext context);
        void OnHeavySpecial(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnRegularParry(InputAction.CallbackContext context);
        void OnNormalParry(InputAction.CallbackContext context);
        void OnSpecialParry(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDirectionalInput(InputAction.CallbackContext context);
        void OnLightNormal(InputAction.CallbackContext context);
        void OnHeavyNormal(InputAction.CallbackContext context);
        void OnLightSpecial(InputAction.CallbackContext context);
        void OnHeavySpecial(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnNormalParry(InputAction.CallbackContext context);
        void OnSpecialParry(InputAction.CallbackContext context);
        void OnGrabParry(InputAction.CallbackContext context);
    }
}
