//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/CharacterControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterControls"",
    ""maps"": [
        {
            ""name"": ""Player 1"",
            ""id"": ""2b7a0304-cf19-46bc-9d9c-c9cfe9ccc2a0"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""d986d784-8635-43f7-9536-a62dc7b3a6d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f475ce92-a30f-4ce9-adbd-ccd043857ad6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""22f119f0-dbae-4d19-8a49-dede3fbb8e41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DirectionalInput"",
                    ""type"": ""Value"",
                    ""id"": ""130dbc91-8acb-4e50-86df-9d9704ed6c70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Light Normal"",
                    ""type"": ""Button"",
                    ""id"": ""f6f509eb-576d-4a06-9c4f-85e1d5685ca9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Normal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b0c7c1a6-e666-4795-bcf0-f08d18c42131"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light Special"",
                    ""type"": ""Button"",
                    ""id"": ""f3186820-a930-446c-9de4-5737518377a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Special"",
                    ""type"": ""Button"",
                    ""id"": ""0bb7ac76-b74c-4e61-b588-06a618144936"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""7334c2e0-962e-4b09-bfec-3b363e42d297"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""5b3d44ed-cc89-4ab1-80ba-7f27ec66cd3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Regular Parry"",
                    ""type"": ""Button"",
                    ""id"": ""085e72da-77e8-4e14-a931-315af809d410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Normal Parry"",
                    ""type"": ""Button"",
                    ""id"": ""83963b68-afc2-46a1-98c4-2f785649bc33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Parry"",
                    ""type"": ""Button"",
                    ""id"": ""7c9faff4-eff0-4b34-bfcb-1edcb3e9e5cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab Parry"",
                    ""type"": ""Button"",
                    ""id"": ""3eac7e06-2f83-4349-be77-7449395540b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard/Horizontal"",
                    ""id"": ""0ad7297e-56d7-47b5-a80b-ef4a18ebb7ee"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9d628b03-f36c-4a04-9531-b53e4742ac56"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a69beb25-26f3-4d24-b5f3-fa8c8f633e14"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-Stick/Horizontal"",
                    ""id"": ""cd9a4497-cae4-4cec-b949-e60ef885bec6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.2,max=1),Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e5e563e3-4879-48b6-8dc7-1fded20a2893"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""919e5b2b-2d72-4794-af68-a4f6d7113a53"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-D-Pad/Horizontal"",
                    ""id"": ""921decd0-161d-46cb-aebf-97b318a97031"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fee59d36-b898-4cef-b67f-620c57d5ae76"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ddc85a3b-8e60-4019-abae-419641a9fdcb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e737280e-d72c-46da-a089-da9d50c4d8f1"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e50514f0-4e18-4df1-ae52-c6c031002264"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard/2DVector"",
                    ""id"": ""e8559e92-2884-4817-9b91-ccdc2add5081"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""57fdc9ee-8f31-470b-b313-631b749b9f59"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""85d4c17d-89cf-4cc6-a885-236cbc972124"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""05392961-6a48-4d49-90c4-eb4189e3ecbc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""749306c0-5f04-45bc-b5c3-80e955fb5f61"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-Stick/2DVector"",
                    ""id"": ""93f185d3-1e70-4975-b33a-8e0857cf04ba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ccbc742-238a-42bc-8a8f-0c69c09fcaf2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0631b3cf-b7c9-47f1-9aaf-f0955940b557"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0ae8b750-7427-4498-861c-ba64bc95ccfe"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9155a25b-9903-4cc1-93fc-58f239c8416e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-D-Pad/2DVector"",
                    ""id"": ""341e34be-29e0-4d1b-a36b-26f6535bdcea"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1f5f13bd-86d2-43df-86c9-82b9c930d99f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bbe61757-b3f8-4a9f-b97a-b155d07d2247"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""da624744-60c0-4628-a162-8be6fc39fca6"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""596ab4ac-0c2c-4024-9cfa-bcb24b7ab8e3"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5f18baa3-3fdf-4034-bbdd-58ad7bf14f13"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb84704d-d3af-407e-a947-f60e24b9912f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff3d69f4-b5ce-4dec-ae5a-d2f0d5c8bfc0"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0296c1fa-50eb-4a83-b0b3-33ff99b31d01"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e876495b-ef92-4d7b-be4a-009eee1558aa"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66d1e88f-d11e-469b-8f70-d693e84e5311"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f250b6bd-ca7d-45fe-8766-06666957cace"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84680f4e-9d27-449b-8713-03fdd0989706"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a33d527-41fd-4cf3-92bc-ae14f0806a55"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4eff7804-3326-4c17-a647-94a330fb5862"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfd9f51-82cc-4dd3-be38-4bfdc855adac"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df845f77-e49b-46f9-9c8e-1fd78345a1e9"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a3748a00-6418-4594-b45d-94497943a244"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""760f7032-c0d4-411b-ab92-8298e76c3796"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""fd408c17-3401-4ea8-b01c-7fc274575a14"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""68f48599-8c9f-4399-b16a-20a37018d39c"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a5da4721-40e6-41c0-ae58-89ee15cf3954"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""909281f5-2c18-4e8b-a3a7-625bb0aff773"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""e51334b1-b092-4e7b-abcb-f87a3794c4a0"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""193c30b4-5ac2-4ef8-ad4c-477eb9bebddb"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""3f6feee2-7360-46fd-a16b-f8279ce0ee0c"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""308ab2da-72b9-48fb-a285-75d3ec942311"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a6e155b3-4cd4-481c-805b-85e9fb078ab0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""32ebf71d-3d04-4777-bee5-32f03eb69fbe"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e865e90c-5e1f-4be0-8e9f-6e424727d268"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86cb8baf-8850-40e5-8132-5b91d8204a7c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""8f3db777-5cae-42f3-ad4e-a7d4ded05a3d"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d1c7f3d9-a730-4e58-a5ad-c9bb2be43823"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""45c3fdc6-1918-4f0b-a9a1-3a8b5bcd22b1"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""27dfdc40-d4b0-498e-9728-10e2d98d2755"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e2a24e52-e849-4125-82bb-93e4130b2e23"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""8de31fd5-b289-431d-9b15-80b8094c52db"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Player 2"",
            ""id"": ""d08a9236-c8b5-4b5b-9c99-c1a4332448b8"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""f16ae7f3-c7e8-453e-9637-5256ede2aa09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2bd7cb35-e11a-4157-bf22-0c8f0cd1bf70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""8973a47f-761e-47f7-bec0-68ba01eb8d64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DirectionalInput"",
                    ""type"": ""Value"",
                    ""id"": ""e1a525c9-e1c0-4063-a835-b57ade2b34a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Light Normal"",
                    ""type"": ""Button"",
                    ""id"": ""25bc7f60-fbc1-4c75-81b1-d8277d169de3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Normal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""27a346b7-ff81-4936-a8df-5e809f8eef61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light Special"",
                    ""type"": ""Button"",
                    ""id"": ""dbc91f3c-87e9-46e5-ab4f-42b68c48d67b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy Special"",
                    ""type"": ""Button"",
                    ""id"": ""3fbc0ade-fc05-440a-9ea9-4fba07c3d970"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""35759bce-9bfd-4e08-bf51-3fce35308e66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""c816b1e5-5d64-4d50-ad87-6ae6c1246cc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Regular Parry"",
                    ""type"": ""Button"",
                    ""id"": ""0d284d81-675f-439a-91d6-61fef438480a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Normal Parry"",
                    ""type"": ""Button"",
                    ""id"": ""eda118de-462e-4e48-800b-4a9dcbd465dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special Parry"",
                    ""type"": ""Button"",
                    ""id"": ""993852c0-a0fd-437c-969d-92604ff30eac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard/Horizontal"",
                    ""id"": ""0395ee17-c438-415f-8f1e-692c397f5940"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c6db2333-e409-4409-a8b6-ac81bf6c3a2e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e9b82c44-157c-4925-aeff-c060a3a07b09"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-Stick/Horizontal"",
                    ""id"": ""67619b9c-7b63-4510-85bc-ed1257772244"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.2,max=1),Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""eb00c9bc-8f5c-4b12-82b6-a04243d87412"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""04420b13-e460-4bb6-98d5-053686d33658"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad-D-Pad/Horizontal"",
                    ""id"": ""1883c465-bacd-4e94-8c63-c1ee5e05ed1f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2782c689-3043-4d54-a12c-d1e29cc85f9b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c17abee7-c610-4e78-960f-b80e871169d3"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""62427715-c459-4000-8e38-e7f14e4e61ef"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65fc879b-0f82-433b-9be5-4af66dbb3da2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard/2DVector"",
                    ""id"": ""4005a4c1-d1a5-41a0-ba56-2c622ebfba67"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e0e0e344-c448-40ab-9c8f-45feb22b4e20"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48291ce4-7e57-41fc-96b5-c0b1462c67ea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d833a5ad-1970-470f-8602-90b82ee54188"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""905cb2ad-9a7a-43b5-b96b-48c23b2724a9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-Stick/2DVector"",
                    ""id"": ""6c92d893-c642-4112-974f-4c8f770a39a6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""90cad67d-9d9d-4b97-b9d4-54854ece236c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""040145de-667b-4b53-853f-71dc9cb1448f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""39be2fec-ccbf-4ec1-902b-7d1607f3f2d7"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a2700053-6b4a-4f91-b129-07b2c489af2f"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamePad-D-Pad/2DVector"",
                    ""id"": ""4ed5a615-c142-4549-8958-3d286a11b2c9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2bc91a95-dd48-4b42-8d3e-925447e1b217"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f385b896-40a1-4bb0-abf5-b9d6d8682529"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a504fd8a-42c7-4b0c-a01d-72ddf9d1e10f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""59489193-9090-47e2-a85b-e463aa0b6353"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DirectionalInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6ca593f1-c56d-4759-ba60-9a62ed0d597a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4d3c329-4bda-4a65-8efd-db3f885d3a33"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f27fbd7-4287-4a4b-9c48-baeb06e8949c"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0d2139b-a250-4367-8787-c303a1fe6eaa"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaa866b7-cd72-4a08-b859-97f356eed07b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a74de1-c7b9-4a94-a85c-7a61a553f4d2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29864409-df57-48ef-a499-6520c82082df"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a83cfa55-096b-469f-8b50-b7ef6e2ebacd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Light Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50870bd1-8430-4947-bf24-e55a67b5746b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74175b38-7aa3-4f0b-be50-bfbba02ac621"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Normal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15086910-a095-4672-bb8d-0972af636060"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46e50c40-0804-4310-a276-e32ec058f327"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heavy Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""d18f064b-1302-48d9-844e-3954ceeaea37"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3bbaf774-abba-4e72-8876-ca0af919ab48"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""484a1309-53a5-4b6b-8016-e05321c2b950"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""4e81ec3d-e407-4c84-a11a-572ec2d744db"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1a8f9591-4f60-4a2d-9bd0-fdaea09d14fa"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""7ce1849a-240d-460f-9f78-4072cae19e76"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Normal Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""cad16675-cb2c-43f9-892a-3ae4a65fe9d7"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""472af532-4db0-453f-ace8-e5b09fb04e3e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""c12886a7-23bf-49fc-a009-b227f98e6e27"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""84d18c1c-1e4f-4e5b-9f44-d9b676d4cafb"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ee371194-a3b2-418c-8c3b-991128956730"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""a40bd123-ff9d-48b3-80dc-493022a0a7df"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3ed3d71a-f0f1-4cac-bdac-730e93c9c4e0"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f8dd7fa-a87e-4a3e-b85f-9f28d910181c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regular Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player 1
        m_Player1 = asset.FindActionMap("Player 1", throwIfNotFound: true);
        m_Player1_Move = m_Player1.FindAction("Move", throwIfNotFound: true);
        m_Player1_Jump = m_Player1.FindAction("Jump", throwIfNotFound: true);
        m_Player1_Dash = m_Player1.FindAction("Dash", throwIfNotFound: true);
        m_Player1_DirectionalInput = m_Player1.FindAction("DirectionalInput", throwIfNotFound: true);
        m_Player1_LightNormal = m_Player1.FindAction("Light Normal", throwIfNotFound: true);
        m_Player1_HeavyNormal = m_Player1.FindAction("Heavy Normal", throwIfNotFound: true);
        m_Player1_LightSpecial = m_Player1.FindAction("Light Special", throwIfNotFound: true);
        m_Player1_HeavySpecial = m_Player1.FindAction("Heavy Special", throwIfNotFound: true);
        m_Player1_Guard = m_Player1.FindAction("Guard", throwIfNotFound: true);
        m_Player1_Grab = m_Player1.FindAction("Grab", throwIfNotFound: true);
        m_Player1_RegularParry = m_Player1.FindAction("Regular Parry", throwIfNotFound: true);
        m_Player1_NormalParry = m_Player1.FindAction("Normal Parry", throwIfNotFound: true);
        m_Player1_SpecialParry = m_Player1.FindAction("Special Parry", throwIfNotFound: true);
        m_Player1_GrabParry = m_Player1.FindAction("Grab Parry", throwIfNotFound: true);
        // Player 2
        m_Player2 = asset.FindActionMap("Player 2", throwIfNotFound: true);
        m_Player2_Move = m_Player2.FindAction("Move", throwIfNotFound: true);
        m_Player2_Jump = m_Player2.FindAction("Jump", throwIfNotFound: true);
        m_Player2_Dash = m_Player2.FindAction("Dash", throwIfNotFound: true);
        m_Player2_DirectionalInput = m_Player2.FindAction("DirectionalInput", throwIfNotFound: true);
        m_Player2_LightNormal = m_Player2.FindAction("Light Normal", throwIfNotFound: true);
        m_Player2_HeavyNormal = m_Player2.FindAction("Heavy Normal", throwIfNotFound: true);
        m_Player2_LightSpecial = m_Player2.FindAction("Light Special", throwIfNotFound: true);
        m_Player2_HeavySpecial = m_Player2.FindAction("Heavy Special", throwIfNotFound: true);
        m_Player2_Guard = m_Player2.FindAction("Guard", throwIfNotFound: true);
        m_Player2_Grab = m_Player2.FindAction("Grab", throwIfNotFound: true);
        m_Player2_RegularParry = m_Player2.FindAction("Regular Parry", throwIfNotFound: true);
        m_Player2_NormalParry = m_Player2.FindAction("Normal Parry", throwIfNotFound: true);
        m_Player2_SpecialParry = m_Player2.FindAction("Special Parry", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player 1
    private readonly InputActionMap m_Player1;
    private IPlayer1Actions m_Player1ActionsCallbackInterface;
    private readonly InputAction m_Player1_Move;
    private readonly InputAction m_Player1_Jump;
    private readonly InputAction m_Player1_Dash;
    private readonly InputAction m_Player1_DirectionalInput;
    private readonly InputAction m_Player1_LightNormal;
    private readonly InputAction m_Player1_HeavyNormal;
    private readonly InputAction m_Player1_LightSpecial;
    private readonly InputAction m_Player1_HeavySpecial;
    private readonly InputAction m_Player1_Guard;
    private readonly InputAction m_Player1_Grab;
    private readonly InputAction m_Player1_RegularParry;
    private readonly InputAction m_Player1_NormalParry;
    private readonly InputAction m_Player1_SpecialParry;
    private readonly InputAction m_Player1_GrabParry;
    public struct Player1Actions
    {
        private @CharacterControls m_Wrapper;
        public Player1Actions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player1_Move;
        public InputAction @Jump => m_Wrapper.m_Player1_Jump;
        public InputAction @Dash => m_Wrapper.m_Player1_Dash;
        public InputAction @DirectionalInput => m_Wrapper.m_Player1_DirectionalInput;
        public InputAction @LightNormal => m_Wrapper.m_Player1_LightNormal;
        public InputAction @HeavyNormal => m_Wrapper.m_Player1_HeavyNormal;
        public InputAction @LightSpecial => m_Wrapper.m_Player1_LightSpecial;
        public InputAction @HeavySpecial => m_Wrapper.m_Player1_HeavySpecial;
        public InputAction @Guard => m_Wrapper.m_Player1_Guard;
        public InputAction @Grab => m_Wrapper.m_Player1_Grab;
        public InputAction @RegularParry => m_Wrapper.m_Player1_RegularParry;
        public InputAction @NormalParry => m_Wrapper.m_Player1_NormalParry;
        public InputAction @SpecialParry => m_Wrapper.m_Player1_SpecialParry;
        public InputAction @GrabParry => m_Wrapper.m_Player1_GrabParry;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnJump;
                @Dash.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDash;
                @DirectionalInput.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnDirectionalInput;
                @LightNormal.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @LightNormal.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @LightNormal.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightNormal;
                @HeavyNormal.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavyNormal;
                @LightSpecial.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnLightSpecial;
                @HeavySpecial.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnHeavySpecial;
                @Guard.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGuard;
                @Grab.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrab;
                @RegularParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @RegularParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @RegularParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnRegularParry;
                @NormalParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @NormalParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @NormalParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnNormalParry;
                @SpecialParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnSpecialParry;
                @GrabParry.started -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabParry;
                @GrabParry.performed -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabParry;
                @GrabParry.canceled -= m_Wrapper.m_Player1ActionsCallbackInterface.OnGrabParry;
            }
            m_Wrapper.m_Player1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @DirectionalInput.started += instance.OnDirectionalInput;
                @DirectionalInput.performed += instance.OnDirectionalInput;
                @DirectionalInput.canceled += instance.OnDirectionalInput;
                @LightNormal.started += instance.OnLightNormal;
                @LightNormal.performed += instance.OnLightNormal;
                @LightNormal.canceled += instance.OnLightNormal;
                @HeavyNormal.started += instance.OnHeavyNormal;
                @HeavyNormal.performed += instance.OnHeavyNormal;
                @HeavyNormal.canceled += instance.OnHeavyNormal;
                @LightSpecial.started += instance.OnLightSpecial;
                @LightSpecial.performed += instance.OnLightSpecial;
                @LightSpecial.canceled += instance.OnLightSpecial;
                @HeavySpecial.started += instance.OnHeavySpecial;
                @HeavySpecial.performed += instance.OnHeavySpecial;
                @HeavySpecial.canceled += instance.OnHeavySpecial;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
                @RegularParry.started += instance.OnRegularParry;
                @RegularParry.performed += instance.OnRegularParry;
                @RegularParry.canceled += instance.OnRegularParry;
                @NormalParry.started += instance.OnNormalParry;
                @NormalParry.performed += instance.OnNormalParry;
                @NormalParry.canceled += instance.OnNormalParry;
                @SpecialParry.started += instance.OnSpecialParry;
                @SpecialParry.performed += instance.OnSpecialParry;
                @SpecialParry.canceled += instance.OnSpecialParry;
                @GrabParry.started += instance.OnGrabParry;
                @GrabParry.performed += instance.OnGrabParry;
                @GrabParry.canceled += instance.OnGrabParry;
            }
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);

    // Player 2
    private readonly InputActionMap m_Player2;
    private IPlayer2Actions m_Player2ActionsCallbackInterface;
    private readonly InputAction m_Player2_Move;
    private readonly InputAction m_Player2_Jump;
    private readonly InputAction m_Player2_Dash;
    private readonly InputAction m_Player2_DirectionalInput;
    private readonly InputAction m_Player2_LightNormal;
    private readonly InputAction m_Player2_HeavyNormal;
    private readonly InputAction m_Player2_LightSpecial;
    private readonly InputAction m_Player2_HeavySpecial;
    private readonly InputAction m_Player2_Guard;
    private readonly InputAction m_Player2_Grab;
    private readonly InputAction m_Player2_RegularParry;
    private readonly InputAction m_Player2_NormalParry;
    private readonly InputAction m_Player2_SpecialParry;
    public struct Player2Actions
    {
        private @CharacterControls m_Wrapper;
        public Player2Actions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player2_Move;
        public InputAction @Jump => m_Wrapper.m_Player2_Jump;
        public InputAction @Dash => m_Wrapper.m_Player2_Dash;
        public InputAction @DirectionalInput => m_Wrapper.m_Player2_DirectionalInput;
        public InputAction @LightNormal => m_Wrapper.m_Player2_LightNormal;
        public InputAction @HeavyNormal => m_Wrapper.m_Player2_HeavyNormal;
        public InputAction @LightSpecial => m_Wrapper.m_Player2_LightSpecial;
        public InputAction @HeavySpecial => m_Wrapper.m_Player2_HeavySpecial;
        public InputAction @Guard => m_Wrapper.m_Player2_Guard;
        public InputAction @Grab => m_Wrapper.m_Player2_Grab;
        public InputAction @RegularParry => m_Wrapper.m_Player2_RegularParry;
        public InputAction @NormalParry => m_Wrapper.m_Player2_NormalParry;
        public InputAction @SpecialParry => m_Wrapper.m_Player2_SpecialParry;
        public InputActionMap Get() { return m_Wrapper.m_Player2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player2Actions set) { return set.Get(); }
        public void SetCallbacks(IPlayer2Actions instance)
        {
            if (m_Wrapper.m_Player2ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnJump;
                @Dash.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDash;
                @DirectionalInput.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @DirectionalInput.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnDirectionalInput;
                @LightNormal.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @LightNormal.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @LightNormal.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightNormal;
                @HeavyNormal.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @HeavyNormal.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavyNormal;
                @LightSpecial.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @LightSpecial.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnLightSpecial;
                @HeavySpecial.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @HeavySpecial.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnHeavySpecial;
                @Guard.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGuard;
                @Grab.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @Grab.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @Grab.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnGrab;
                @RegularParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnRegularParry;
                @RegularParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnRegularParry;
                @RegularParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnRegularParry;
                @NormalParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @NormalParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @NormalParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnNormalParry;
                @SpecialParry.started -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.performed -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
                @SpecialParry.canceled -= m_Wrapper.m_Player2ActionsCallbackInterface.OnSpecialParry;
            }
            m_Wrapper.m_Player2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @DirectionalInput.started += instance.OnDirectionalInput;
                @DirectionalInput.performed += instance.OnDirectionalInput;
                @DirectionalInput.canceled += instance.OnDirectionalInput;
                @LightNormal.started += instance.OnLightNormal;
                @LightNormal.performed += instance.OnLightNormal;
                @LightNormal.canceled += instance.OnLightNormal;
                @HeavyNormal.started += instance.OnHeavyNormal;
                @HeavyNormal.performed += instance.OnHeavyNormal;
                @HeavyNormal.canceled += instance.OnHeavyNormal;
                @LightSpecial.started += instance.OnLightSpecial;
                @LightSpecial.performed += instance.OnLightSpecial;
                @LightSpecial.canceled += instance.OnLightSpecial;
                @HeavySpecial.started += instance.OnHeavySpecial;
                @HeavySpecial.performed += instance.OnHeavySpecial;
                @HeavySpecial.canceled += instance.OnHeavySpecial;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
                @RegularParry.started += instance.OnRegularParry;
                @RegularParry.performed += instance.OnRegularParry;
                @RegularParry.canceled += instance.OnRegularParry;
                @NormalParry.started += instance.OnNormalParry;
                @NormalParry.performed += instance.OnNormalParry;
                @NormalParry.canceled += instance.OnNormalParry;
                @SpecialParry.started += instance.OnSpecialParry;
                @SpecialParry.performed += instance.OnSpecialParry;
                @SpecialParry.canceled += instance.OnSpecialParry;
            }
        }
    }
    public Player2Actions @Player2 => new Player2Actions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayer1Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDirectionalInput(InputAction.CallbackContext context);
        void OnLightNormal(InputAction.CallbackContext context);
        void OnHeavyNormal(InputAction.CallbackContext context);
        void OnLightSpecial(InputAction.CallbackContext context);
        void OnHeavySpecial(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnRegularParry(InputAction.CallbackContext context);
        void OnNormalParry(InputAction.CallbackContext context);
        void OnSpecialParry(InputAction.CallbackContext context);
        void OnGrabParry(InputAction.CallbackContext context);
    }
    public interface IPlayer2Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDirectionalInput(InputAction.CallbackContext context);
        void OnLightNormal(InputAction.CallbackContext context);
        void OnHeavyNormal(InputAction.CallbackContext context);
        void OnLightSpecial(InputAction.CallbackContext context);
        void OnHeavySpecial(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
        void OnRegularParry(InputAction.CallbackContext context);
        void OnNormalParry(InputAction.CallbackContext context);
        void OnSpecialParry(InputAction.CallbackContext context);
    }
}
